### ISSUE TITLE
Proposal: Style Guide

### ISSUE THREAD

**Issue by dan-f** [edx/edx-ui-toolkit#32]
I'd like to propose that we design an explicit style guide for this project.

## Motivation:
- Consistency makes new code approachable and easy to read
- Can help prevent common JS bugs
- Makes contributing more accessible; e.g. sane indentation means you can contribute no matter what editor you use
- Avoids ambiguity

## Scope
- Naming (file names, require module names, "class" names, variable names)
- AMD module declaration style
- Testing style
- Variable declarations (hoisting, functions as variables vs function statements)
- Indentation (number of spaces, how to break lines)
- Paren and brace style

## Examples

- Airbnb has a [comprehensive style guide](https://github.com/airbnb/javascript)
- Google [has one too](https://google.github.io/styleguide/javascriptguide.xml)

**Comment by andy-armstrong** [comment]
Closing this in favor of https://openedx.atlassian.net/browse/DOC-2755

**Comment by dan-f** [comment]
I don't agree with closing this ticket. That DOC ticket is clearly "high-level guidance" while a style guide is necessarily lower level syntax reference.

**Comment by pdesjardins** [comment]
@dan-f You're right about the way that DOC ticket is labeled. However, as I worked on the developer's guide section for that documentation project, I started migrating the JavaScript style guide information into the dev guide (alongside our Python and Objective C style guides).

I think the JavaScript style information you're describing would fit with the draft JavaScript style guide content I'm trying to merge in https://github.com/edx/edx-documentation/pull/906.

You can see the draft here: http://draft-fedx-dev-doc.readthedocs.io/en/latest/style_guides/javascript_guidelines.html.

**Comment by andy-armstrong** [comment]
@dan-f Sorry that I didn't give enough context when closing this ticket. The FedX team and @pdesjardins have had a lot of discussions over the past few months about the right way to consolidate all the JavaScript documentation that we have in multiple places. We settled on using the Developer Guide as the central repository, and so given that IMO we shouldn't be creating any new per-repository material unless it really is unique. I completely agree about the need for a centralized style guide a la Google and AirBnB, and this is why @pdesjardins is spearheading this work in the Developer Guide.
